# ---------------------------------------------------------
# ARQUIVO: docker-compose.yml (Raiz)
# ATENÇÃO: Este arquivo atua como um redirecionador.
# Por padrão, ele carrega o ambiente de DESENVOLVIMENTO.
# 
# Para rodar produção, use:
# docker compose -f docker-compose.prod.yml up -d
# ---------------------------------------------------------
include:
  - docker-compose.dev.yml
