"""make_assets_global

Revision ID: 3d7520742986
Revises: ca873db2979f
Create Date: 2026-07-16 16:52:04.190028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7520742986'
down_revision: Union[str, Sequence[str], None] = 'ca873db2979f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets') as batch_op:
        batch_op.drop_constraint('_ticker_user_uc', type_='unique')
        batch_op.drop_index('ix_assets_user_id')
        batch_op.drop_index('ix_assets_ticker')
        batch_op.create_index('ix_assets_ticker', ['ticker'], unique=True)
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_assets_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('ix_assets_ticker')
        batch_op.create_index('ix_assets_ticker', ['ticker'], unique=False)
        batch_op.create_index('ix_assets_user_id', ['user_id'], unique=False)
        batch_op.create_unique_constraint('_ticker_user_uc', ['ticker', 'user_id'])
    # ### end Alembic commands ###
