"""make_assets_global

Revision ID: 3d7520742986
Revises: ca873db2979f
Create Date: 2026-07-16 16:52:04.190028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7520742986'
down_revision: Union[str, Sequence[str], None] = 'ca873db2979f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    import sqlalchemy as _sa

    bind = op.get_bind()
    inspector = _sa.inspect(bind)

    # Collect existing unique constraints and indexes on 'assets'
    existing_ucs = {uc['name'] for uc in inspector.get_unique_constraints('assets')}
    existing_idxs = {idx['name'] for idx in inspector.get_indexes('assets')}

    with op.batch_alter_table('assets') as batch_op:
        if '_ticker_user_uc' in existing_ucs:
            batch_op.drop_constraint('_ticker_user_uc', type_='unique')
        if 'ix_assets_user_id' in existing_idxs:
            batch_op.drop_index('ix_assets_user_id')
        if 'ix_assets_ticker' in existing_idxs:
            batch_op.drop_index('ix_assets_ticker')
        batch_op.create_index('ix_assets_ticker', ['ticker'], unique=True)

    # Only drop user_id column if it still exists
    existing_cols = {col['name'] for col in inspector.get_columns('assets')}
    if 'user_id' in existing_cols:
        with op.batch_alter_table('assets') as batch_op:
            batch_op.drop_column('user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_assets_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('ix_assets_ticker')
        batch_op.create_index('ix_assets_ticker', ['ticker'], unique=False)
        batch_op.create_index('ix_assets_user_id', ['user_id'], unique=False)
        batch_op.create_unique_constraint('_ticker_user_uc', ['ticker', 'user_id'])
    # ### end Alembic commands ###
