"""initial_schema

Revision ID: 70c6edf66856
Revises: 
Create Date: 2026-07-07 20:26:54.052401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c6edf66856'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela_afetada', sa.String(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('campo_alterado', sa.String(), nullable=False),
    sa.Column('valor_antigo', sa.String(), nullable=True),
    sa.Column('valor_novo', sa.String(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_percent', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_states',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('system_caches',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('triggered_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggered_alerts_is_notified'), 'triggered_alerts', ['is_notified'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_chat_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_histories_session_id'), 'ai_chat_histories', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_histories_user_id'), 'ai_chat_histories', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('cvm_code', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('ai_sentiment', sa.String(), nullable=True),
    sa.Column('ai_status', sa.String(), nullable=True),
    sa.Column('ai_updated_at', sa.DateTime(), nullable=True),
    sa.Column('upcoming_split', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'user_id', name='_ticker_user_uc')
    )
    op.create_index(op.f('ix_assets_category_id'), 'assets', ['category_id'], unique=False)
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('limit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_cards_user_deleted', 'credit_cards', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_credit_cards_user_id'), 'credit_cards', ['user_id'], unique=False)
    op.create_table('debtors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'user_id', name='_debtor_nome_user_uc')
    )
    op.create_index('idx_debtors_user_deleted', 'debtors', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_debtors_user_id'), 'debtors', ['user_id'], unique=False)
    op.create_table('refund_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fechamento_dia', sa.Integer(), nullable=True),
    sa.Column('vencimento_dia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_configs_user_id'), 'refund_configs', ['user_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_invested', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('profit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_date'), 'snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_snapshots_user_id'), 'snapshots', ['user_id'], unique=False)
    op.create_table('card_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('installments_count', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_card_expenses_user_deleted', 'card_expenses', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_card_expenses_user_id'), 'card_expenses', ['user_id'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_com', sa.Date(), nullable=False),
    sa.Column('date_payment', sa.Date(), nullable=True),
    sa.Column('value_per_share', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_at_date', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dividends_asset_date_com', 'dividends', ['asset_id', 'date_com'], unique=False)
    op.create_index(op.f('ix_dividends_asset_id'), 'dividends', ['asset_id'], unique=False)
    op.create_index(op.f('ix_dividends_date_com'), 'dividends', ['date_com'], unique=False)
    op.create_index(op.f('ix_dividends_user_id'), 'dividends', ['user_id'], unique=False)
    op.create_table('fixed_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('index_type', sa.String(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'user_id', name='_fixed_income_asset_user_uc')
    )
    op.create_index('idx_fixed_income_user_deleted', 'fixed_income', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_fixed_income_user_id'), 'fixed_income', ['user_id'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('min_6m', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sma_20', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_data_asset_date', 'market_data', ['asset_id', 'date'], unique=False)
    op.create_index(op.f('ix_market_data_asset_id'), 'market_data', ['asset_id'], unique=False)
    op.create_index(op.f('ix_market_data_date'), 'market_data', ['date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_percent', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('manual_lpa', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('manual_vpa', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('manual_dy', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_report_url', sa.String(), nullable=True),
    sa.Column('last_report_at', sa.String(), nullable=True),
    sa.Column('last_report_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'user_id', name='_asset_user_uc')
    )
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_asset_id'), 'price_alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_price_alerts_is_active'), 'price_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_price_alerts_user_id'), 'price_alerts', ['user_id'], unique=False)
    op.create_table('receivable_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('data_emprestimo', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_parcelado', sa.Boolean(), nullable=True),
    sa.Column('total_parcelas', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('fatura_mes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_receivable_loans_user_deleted', 'receivable_loans', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_receivable_loans_user_id'), 'receivable_loans', ['user_id'], unique=False)
    op.create_table('card_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('invoice_month', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['card_expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_card_installments_user_deleted', 'card_installments', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_card_installments_user_id'), 'card_installments', ['user_id'], unique=False)
    op.create_table('loan_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_efetiva_pagamento', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('fatura_mes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['receivable_loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_loan_installments_user_deleted', 'loan_installments', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_loan_installments_user_id'), 'loan_installments', ['user_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.Column('tipo_movimentacao', sa.String(), nullable=False),
    sa.Column('forma_pagamento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['installment_id'], ['loan_installments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_loan_installments_user_id'), table_name='loan_installments')
    op.drop_index('idx_loan_installments_user_deleted', table_name='loan_installments')
    op.drop_table('loan_installments')
    op.drop_index(op.f('ix_card_installments_user_id'), table_name='card_installments')
    op.drop_index('idx_card_installments_user_deleted', table_name='card_installments')
    op.drop_table('card_installments')
    op.drop_index(op.f('ix_receivable_loans_user_id'), table_name='receivable_loans')
    op.drop_index('idx_receivable_loans_user_deleted', table_name='receivable_loans')
    op.drop_table('receivable_loans')
    op.drop_index(op.f('ix_price_alerts_user_id'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_is_active'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_asset_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_market_data_date'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_asset_id'), table_name='market_data')
    op.drop_index('idx_market_data_asset_date', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_fixed_income_user_id'), table_name='fixed_income')
    op.drop_index('idx_fixed_income_user_deleted', table_name='fixed_income')
    op.drop_table('fixed_income')
    op.drop_index(op.f('ix_dividends_user_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_date_com'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_asset_id'), table_name='dividends')
    op.drop_index('idx_dividends_asset_date_com', table_name='dividends')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_card_expenses_user_id'), table_name='card_expenses')
    op.drop_index('idx_card_expenses_user_deleted', table_name='card_expenses')
    op.drop_table('card_expenses')
    op.drop_index(op.f('ix_snapshots_user_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_date'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_refund_configs_user_id'), table_name='refund_configs')
    op.drop_table('refund_configs')
    op.drop_index(op.f('ix_debtors_user_id'), table_name='debtors')
    op.drop_index('idx_debtors_user_deleted', table_name='debtors')
    op.drop_table('debtors')
    op.drop_index(op.f('ix_credit_cards_user_id'), table_name='credit_cards')
    op.drop_index('idx_credit_cards_user_deleted', table_name='credit_cards')
    op.drop_table('credit_cards')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_index(op.f('ix_assets_category_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_ai_chat_histories_user_id'), table_name='ai_chat_histories')
    op.drop_index(op.f('ix_ai_chat_histories_session_id'), table_name='ai_chat_histories')
    op.drop_table('ai_chat_histories')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_triggered_alerts_is_notified'), table_name='triggered_alerts')
    op.drop_table('triggered_alerts')
    op.drop_table('system_caches')
    op.drop_table('sync_states')
    op.drop_table('categories')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
