"""Add tax models and cost_basis

Revision ID: 94d37fc6c37c
Revises: affbf294de48
Create Date: 2026-07-21 19:13:09.288626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d37fc6c37c'
down_revision: Union[str, Sequence[str], None] = 'affbf294de48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accumulated_loss_stocks_st', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('accumulated_loss_stocks_dt', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('accumulated_loss_fiis', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('accumulated_darf_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_profiles_user_id'), 'tax_profiles', ['user_id'], unique=True)
    op.add_column('asset_transactions', sa.Column('cost_basis', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('asset_transactions', sa.Column('is_day_trade', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_transactions', 'is_day_trade')
    op.drop_column('asset_transactions', 'cost_basis')
    op.drop_index(op.f('ix_tax_profiles_user_id'), table_name='tax_profiles')
    op.drop_table('tax_profiles')
    # ### end Alembic commands ###
