"""initial_schema

Revision ID: 9d180fb19a1b
Revises: 
Create Date: 2026-06-28 05:10:18.414466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d180fb19a1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'ai_summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assets', 'ai_sentiment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assets', 'ai_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'idle'"))
    op.create_index(op.f('ix_assets_category_id'), 'assets', ['category_id'], unique=False)
    op.alter_column('categories', 'target_percent',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('dividends', 'value_per_share',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('dividends', 'quantity_at_date',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('dividends', 'total_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.create_index('idx_dividends_asset_date_com', 'dividends', ['asset_id', 'date_com'], unique=False)
    op.create_index('idx_dividends_asset_date_com_desc', 'dividends', ['asset_id', 'date_com'], unique=False)
    op.create_index(op.f('ix_dividends_asset_id'), 'dividends', ['asset_id'], unique=False)
    op.create_index(op.f('ix_dividends_date_com'), 'dividends', ['date_com'], unique=False)
    op.alter_column('market_data', 'price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('market_data', 'min_6m',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('market_data', 'change_percent',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('market_data', 'rsi_14',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('market_data', 'sma_20',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.create_index('idx_market_data_asset_date', 'market_data', ['asset_id', 'date'], unique=False)
    op.create_index('idx_market_data_asset_date_desc', 'market_data', ['asset_id', 'date'], unique=False)
    op.create_index(op.f('ix_market_data_asset_id'), 'market_data', ['asset_id'], unique=False)
    op.create_index(op.f('ix_market_data_date'), 'market_data', ['date'], unique=False)
    op.alter_column('positions', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('positions', 'average_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('positions', 'target_percent',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('positions', 'manual_lpa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('positions', 'manual_vpa',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('positions', 'manual_dy',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('price_alerts', 'target_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('receivables', 'valor_parcela',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('snapshots', 'total_equity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('snapshots', 'total_invested',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('snapshots', 'profit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
    op.create_index(op.f('ix_snapshots_date'), 'snapshots', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_date'), table_name='snapshots')
    op.alter_column('snapshots', 'profit',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('snapshots', 'total_invested',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('snapshots', 'total_equity',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('receivables', 'valor_parcela',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('price_alerts', 'target_price',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('positions', 'manual_dy',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('positions', 'manual_vpa',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('positions', 'manual_lpa',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('positions', 'target_percent',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('positions', 'average_price',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('positions', 'quantity',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_market_data_date'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_asset_id'), table_name='market_data')
    op.drop_index('idx_market_data_asset_date_desc', table_name='market_data')
    op.drop_index('idx_market_data_asset_date', table_name='market_data')
    op.alter_column('market_data', 'sma_20',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('market_data', 'rsi_14',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('market_data', 'change_percent',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('market_data', 'min_6m',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('market_data', 'price',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_dividends_date_com'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_asset_id'), table_name='dividends')
    op.drop_index('idx_dividends_asset_date_com_desc', table_name='dividends')
    op.drop_index('idx_dividends_asset_date_com', table_name='dividends')
    op.alter_column('dividends', 'total_value',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dividends', 'quantity_at_date',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dividends', 'value_per_share',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('categories', 'target_percent',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_assets_category_id'), table_name='assets')
    op.alter_column('assets', 'ai_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'idle'"))
    op.alter_column('assets', 'ai_sentiment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'ai_summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
