"""add_refund_module

Revision ID: c330f6b5d746
Revises: 9d180fb19a1b
Create Date: 2026-07-03 03:25:37.384771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c330f6b5d746'
down_revision: Union[str, Sequence[str], None] = '9d180fb19a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela_afetada', sa.String(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('campo_alterado', sa.String(), nullable=False),
    sa.Column('valor_antigo', sa.String(), nullable=True),
    sa.Column('valor_novo', sa.String(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debtors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_debtors_id'), 'debtors', ['id'], unique=False)
    op.create_table('refund_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechamento_dia', sa.Integer(), nullable=True),
    sa.Column('vencimento_dia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receivable_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('data_emprestimo', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_parcelado', sa.Boolean(), nullable=True),
    sa.Column('total_parcelas', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('fatura_mes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivable_loans_id'), 'receivable_loans', ['id'], unique=False)
    op.create_table('loan_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_efetiva_pagamento', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('fatura_mes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['receivable_loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_installments_id'), 'loan_installments', ['id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.Column('tipo_movimentacao', sa.String(), nullable=False),
    sa.Column('forma_pagamento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['installment_id'], ['loan_installments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    
    # SQLite does not support standard index dropping via index object in autogenerated scripts sometimes,
    # so we drop indexes by name on the tables being dropped
    try:
        op.drop_index('ix_receivables_id', table_name='receivables')
    except Exception:
        pass
    try:
        op.drop_table('receivables')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receivables',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(), nullable=True),
    sa.Column('devedor', sa.VARCHAR(), nullable=True),
    sa.Column('valor_parcela', sa.FLOAT(), nullable=True),
    sa.Column('parcela_atual', sa.INTEGER(), nullable=True),
    sa.Column('total_parcelas', sa.INTEGER(), nullable=True),
    sa.Column('vencimento_dia', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('last_payment_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_receivables_id', 'receivables', ['id'], unique=False)
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_loan_installments_id'), table_name='loan_installments')
    op.drop_table('loan_installments')
    op.drop_index(op.f('ix_receivable_loans_id'), table_name='receivable_loans')
    op.drop_table('receivable_loans')
    op.drop_table('refund_configs')
    op.drop_index(op.f('ix_debtors_id'), table_name='debtors')
    op.drop_table('debtors')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
