import os
import re

migration_file = '/app/server/alembic/versions/8d02bf9b0d6a_add_options_schema.py'

with open(migration_file, 'r') as f:
    content = f.read()

# Replace upgrade() function
upgrade_code = """def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_option', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('option_meta', sa.JSON(), nullable=True))

    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_percent', sa.Numeric(precision=18, scale=4), nullable=True))
        batch_op.add_column(sa.Column('raw_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###"""

downgrade_code = """def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.drop_column('raw_data')
        batch_op.drop_column('cost_percent')

    with op.batch_alter_table('asset_transactions', schema=None) as batch_op:
        batch_op.drop_column('option_meta')
        batch_op.drop_column('is_option')
    # ### end Alembic commands ###"""

new_content = re.sub(r'def upgrade\(\) -> None:.*?(?=def downgrade)', upgrade_code + '\n\n', content, flags=re.DOTALL)
new_content = re.sub(r'def downgrade\(\) -> None:.*', downgrade_code + '\n', new_content, flags=re.DOTALL)

with open(migration_file, 'w') as f:
    f.write(new_content)
